services:
  - type: web
    name: car-api
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: car-api-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: POSTGRES_HOST
        fromDatabase:
          name: car-api-db
          property: host
      - key: POSTGRES_USER
        fromDatabase:
          name: car-api-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: car-api-db
          property: password
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: car-api-db
          property: database
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: car-api-db
    databaseName: car_api_production
    user: car_api
    plan: free